#!/bin/bash

echo "Setting e"
set -e

echo "Initializing variables..."
CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
echo "Syncing submodule..."
git -C "${DOTBOT_DIR}" submodule sync --recursive
echo "Updating submodule..."
git submodule update --init --recursive "${DOTBOT_DIR}"

echo "Installing dots..."
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
